# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bluectl < Formula
  desc "The official command line interface for Alphaus services."
  homepage "https://github.com/alphauslabs/bluectl"
  version "0.34.18"

  on_macos do
    url "https://github.com/alphauslabs/bluectl/releases/download/v0.34.18/bluectl_0.34.18_darwin_amd64.tar.gz"
    sha256 "0571886936df203d5afabad5d88a5c6abe9f8295b5263f7987bfc5eb62664a31"

    def install
      bin.install "bluectl"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Bluectl
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/alphauslabs/bluectl/releases/download/v0.34.18/bluectl_0.34.18_linux_amd64.tar.gz"
        sha256 "ce9f6a773887dbbe389cdf8d97346f3c35b584a51371d302fc8a037c89952862"

        def install
          bin.install "bluectl"
        end
      end
    end
  end

  test do
    assert_match /Command line interface for Alphaus/, shell_output("#{bin}/bluectl -h", 0)
  end
end
