# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bluectl < Formula
  desc "The official command line interface for Alphaus services."
  homepage "https://github.com/alphauslabs/bluectl"
  version "0.34.2"

  on_macos do
    url "https://github.com/alphauslabs/bluectl/releases/download/v0.34.2/bluectl_0.34.2_darwin_amd64.tar.gz"
    sha256 "c5b13f48e61273f5de447e5bd629dcce8cdf584a29c2a34c4c1709febe9601e4"

    def install
      bin.install "bluectl"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Bluectl
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/alphauslabs/bluectl/releases/download/v0.34.2/bluectl_0.34.2_linux_amd64.tar.gz"
      sha256 "eaaf7e157f32c959f65c4456fed4bc127f0684bec7a54b9f1c6e2019fed28c30"

      def install
        bin.install "bluectl"
      end
    end
  end

  test do
    assert_match /Command line interface for Alphaus/, shell_output("#{bin}/bluectl -h", 0)
  end
end
