# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bluectl < Formula
  desc "The official command line interface for Alphaus services."
  homepage "https://github.com/alphauslabs/bluectl"
  version "0.34.9"

  on_macos do
    url "https://github.com/alphauslabs/bluectl/releases/download/v0.34.9/bluectl_0.34.9_darwin_amd64.tar.gz"
    sha256 "4866ed49e78713d0c4a567aaf4ec9988215e024200301145fe43d958a3f86a42"

    def install
      bin.install "bluectl"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Bluectl
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/alphauslabs/bluectl/releases/download/v0.34.9/bluectl_0.34.9_linux_amd64.tar.gz"
      sha256 "777e5b902cd07cd2a12dc5d5d688ae6e0a7002f58cb0c6ce9c1fce24a7a5b79a"

      def install
        bin.install "bluectl"
      end
    end
  end

  test do
    assert_match /Command line interface for Alphaus/, shell_output("#{bin}/bluectl -h", 0)
  end
end
