# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Budget < Formula
  desc "The official command line interface for Alphaus internal budget service."
  homepage "https://github.com/alphauslabs/budget"
  version "0.1.0"

  on_macos do
    url "https://github.com/alphauslabs/budget/releases/download/v0.1.0/budget_0.1.0_darwin_amd64.tar.gz"
    sha256 "87bf821cb9d16b949bf60ddc596019e9adab5d49908c7b4c98cfe08e33dd65b8"

    def install
      bin.install "budget"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Budget
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/alphauslabs/budget/releases/download/v0.1.0/budget_0.1.0_linux_amd64.tar.gz"
      sha256 "ce3302403b1a01648381c31473fe0ad6f4a6be36696d492f4bd1c02215ec660c"

      def install
        bin.install "budget"
      end
    end
  end

  test do
    assert_match /Command line interface for /, shell_output("#{bin}/budget -h", 0)
  end
end
