# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Budget < Formula
  desc "The official command line interface for Alphaus internal budget service."
  homepage "https://github.com/alphauslabs/budget"
  version "0.1.1"

  on_macos do
    url "https://github.com/alphauslabs/budget/releases/download/v0.1.1/budget_0.1.1_darwin_amd64.tar.gz"
    sha256 "b0a3520b9c7127a2fbd3c9c095a9d0c22b2997f1c2473c5aee3bbdc3f575ee5c"

    def install
      bin.install "budget"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Budget
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/alphauslabs/budget/releases/download/v0.1.1/budget_0.1.1_linux_amd64.tar.gz"
      sha256 "1ca601ad334d7f379c2b05a3a5a3ddbea0f5a6fb8aa015d419b0416fe0a20cd4"

      def install
        bin.install "budget"
      end
    end
  end

  test do
    assert_match /Command line interface for /, shell_output("#{bin}/budget -h", 0)
  end
end
