# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Iam < Formula
  desc "The official command line interface for Alphaus internal IAM service."
  homepage "https://github.com/alphauslabs/iam"
  version "0.4.5"

  on_macos do
    url "https://github.com/alphauslabs/iam/releases/download/v0.4.5/iam_0.4.5_darwin_amd64.tar.gz"
    sha256 "cdf365e814055c712fca69e7552cd8ab1cd27ca2da6d81adcd46b2ba5f779d76"

    def install
      bin.install "iam"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Iam
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/alphauslabs/iam/releases/download/v0.4.5/iam_0.4.5_linux_amd64.tar.gz"
      sha256 "d9a79ce9697dd87c0ce53fc48f14ce388f1d512ff895bdc86dc0a8fbbed56d7d"

      def install
        bin.install "iam"
      end
    end
  end

  test do
    assert_match /Command line interface for /, shell_output("#{bin}/iam -h", 0)
  end
end
