# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Iam < Formula
  desc "The official command line interface for Alphaus internal IAM service."
  homepage "https://github.com/alphauslabs/iam"
  version "0.4.7"

  on_macos do
    url "https://github.com/alphauslabs/iam/releases/download/v0.4.7/iam_0.4.7_darwin_amd64.tar.gz"
    sha256 "d7ed69ff5643e8cf23d518b539413ef3af953ad824a806c2b04ddca4a71a4f02"

    def install
      bin.install "iam"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Iam
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/alphauslabs/iam/releases/download/v0.4.7/iam_0.4.7_linux_amd64.tar.gz"
      sha256 "e1c84c81bbece8b2a61d958fd571b5742107938c3180ee7b63a3a00efc54e8f2"
      def install
        bin.install "iam"
      end
    end
  end

  test do
    assert_match /Command line interface for /, shell_output("#{bin}/iam -h", 0)
  end
end
