# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Iam < Formula
  desc "The official command line interface for Alphaus internal IAM service."
  homepage "https://github.com/alphauslabs/iam"
  version "0.4.3"

  on_macos do
    url "https://github.com/alphauslabs/iam/releases/download/v0.4.3/iam_0.4.3_darwin_amd64.tar.gz"
    sha256 "c289180b0a73d17ab26c00b1c3cebfc755453691c2da67540734f622a2b723ad"

    def install
      bin.install "iam"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Iam
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/alphauslabs/iam/releases/download/v0.4.3/iam_0.4.3_linux_amd64.tar.gz"
      sha256 "95e2bcdc2abcbf1a55186f1e9796aa26869195a644cf8b6f64729ec7e0844276"

      def install
        bin.install "iam"
      end
    end
  end

  test do
    assert_match /Command line interface for /, shell_output("#{bin}/iam -h", 0)
  end
end
