# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oops < Formula
  desc "Kubernetes-native testing tool."
  homepage "https://github.com/alphauslabs/oops"
  version "1.2.35"

  on_macos do
    url "https://github.com/alphauslabs/oops/releases/download/v1.2.35/oops_1.2.35_darwin_amd64.tar.gz"
    sha256 "038988e3aa3d99dff8aad2775f8137e64e98265bc8f7621a688fefc92d59bb0c"

    define_method(:install) do
      bin.install "oops"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Oops
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alphauslabs/oops/releases/download/v1.2.35/oops_1.2.35_linux_amd64.tar.gz"
      sha256 "9a176c48e48b6a73a15681a30e12e311e9029273d9b4ce3d96df2060c9a9ba8e"
      define_method(:install) do
        bin.install "oops"
      end
    end
  end

  test do
    assert_match /Kubernetes-native testing tool/, shell_output("#{bin}/oops -h", 0)
  end
end
