# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oops < Formula
  desc "Kubernetes-native testing tool."
  homepage "https://github.com/alphauslabs/oops"
  version "1.2.45"

  on_macos do
    url "https://github.com/alphauslabs/oops/releases/download/v1.2.45/oops_1.2.45_darwin_amd64.tar.gz"
    sha256 "d5c3f0e65d6cbaca01099fcc9c950ee6980cbf8c64b301c33fb0843b2812555a"

    define_method(:install) do
      bin.install "oops"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Oops
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alphauslabs/oops/releases/download/v1.2.45/oops_1.2.45_linux_amd64.tar.gz"
      sha256 "19eeb3b94e209fdd0fd05072319806b26e4bd5ff4cbae72720b4d4c359a56ff3"
      define_method(:install) do
        bin.install "oops"
      end
    end
  end

  test do
    assert_match /Kubernetes-native testing tool/, shell_output("#{bin}/oops -h", 0)
  end
end
