# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oops < Formula
  desc "Kubernetes-native testing tool."
  homepage "https://github.com/alphauslabs/oops"
  version "1.2.41"

  on_macos do
    url "https://github.com/alphauslabs/oops/releases/download/v1.2.41/oops_1.2.41_darwin_amd64.tar.gz"
    sha256 "b184cd94eb629b7a5d04d783ff1b6606875406d56b2ed9015c684bbbfec62154"

    define_method(:install) do
      bin.install "oops"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Oops
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alphauslabs/oops/releases/download/v1.2.41/oops_1.2.41_linux_amd64.tar.gz"
      sha256 "922601ffc321185f91b5f6f43583cff3d3603d29ae216d10bd88ee3d4e359011"
      define_method(:install) do
        bin.install "oops"
      end
    end
  end

  test do
    assert_match /Kubernetes-native testing tool/, shell_output("#{bin}/oops -h", 0)
  end
end
