# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ops < Formula
  desc "The official command line interface for Alphaus long operations service."
  homepage "https://github.com/alphauslabs/ops"
  version "0.1.2"

  on_macos do
    url "https://github.com/alphauslabs/ops/releases/download/v0.1.2/ops_0.1.2_darwin_amd64.tar.gz"
    sha256 "769ffd5abd49d96eb9e27f68b46559ed02b326152fc6b6354ff016f310a8eb5a"

    def install
      bin.install "ops"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Ops
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/alphauslabs/ops/releases/download/v0.1.2/ops_0.1.2_linux_amd64.tar.gz"
      sha256 "ce076d16c3c7198cae1bee2cf4c44598fda43f409a5b3c2ca6262a3d744efbb1"

      def install
        bin.install "ops"
      end
    end
  end

  test do
    assert_match /Command line interface for /, shell_output("#{bin}/ops -h", 0)
  end
end
