# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ops < Formula
  desc "The official command line interface for Alphaus long operations service."
  homepage "https://github.com/alphauslabs/ops"
  version "0.2.1"

  on_macos do
    url "https://github.com/alphauslabs/ops/releases/download/v0.2.1/ops_0.2.1_darwin_amd64.tar.gz"
    sha256 "a3c15bdb848a1cf3ae694cc3d5760a2f7e05814c0800e4fbb14b089df02b001f"

    def install
      bin.install "ops"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Ops
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/alphauslabs/ops/releases/download/v0.2.1/ops_0.2.1_linux_amd64.tar.gz"
      sha256 "6c5ad03ed5cc23ec52d30c7dc782a1a60c58e3c242f085ee5f273e1715b00c43"

      def install
        bin.install "ops"
      end
    end
  end

  test do
    assert_match /Command line interface for /, shell_output("#{bin}/ops -h", 0)
  end
end
