# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ops < Formula
  desc "The official command line interface for Alphaus long operations service."
  homepage "https://github.com/alphauslabs/ops"
  version "0.2.0"

  on_macos do
    url "https://github.com/alphauslabs/ops/releases/download/v0.2.0/ops_0.2.0_darwin_amd64.tar.gz"
    sha256 "24082d191902581dc4e002affb2a60343f43cb185052dc7f23c715f07cb27613"

    def install
      bin.install "ops"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Ops
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/alphauslabs/ops/releases/download/v0.2.0/ops_0.2.0_linux_amd64.tar.gz"
      sha256 "d26aa6aad84fb3a9e8354c0191448641b861f34714a10a80a65e310c676a46f1"

      def install
        bin.install "ops"
      end
    end
  end

  test do
    assert_match /Command line interface for /, shell_output("#{bin}/ops -h", 0)
  end
end
