# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tucp < Formula
  desc "The official command line interface for Alphaus TrueUnblended Control Plane service."
  homepage "https://github.com/alphauslabs/tucp"
  version "0.4.0"

  on_macos do
    url "https://github.com/alphauslabs/tucp/releases/download/v0.4.0/tucp_0.4.0_darwin_amd64.tar.gz"
    sha256 "cb05a70ce18d9952872c01091abb1483799c480569dc3d7ed8448ac2044a6182"

    def install
      bin.install "tucp"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Tucp
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/alphauslabs/tucp/releases/download/v0.4.0/tucp_0.4.0_linux_amd64.tar.gz"
      sha256 "5db17b873b195a7f6978501a3e7d0d3f2c4a124e07cae8b7a5952164991c833f"

      def install
        bin.install "tucp"
      end
    end
  end

  test do
    assert_match /Command line interface for /, shell_output("#{bin}/tucp -h", 0)
  end
end
