# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tucp < Formula
  desc "The official command line interface for Alphaus TrueUnblended Control Plane service."
  homepage "https://github.com/alphauslabs/tucp"
  version "0.1.1"

  on_macos do
    url "https://github.com/alphauslabs/tucp/releases/download/v0.1.1/tucp_0.1.1_darwin_amd64.tar.gz"
    sha256 "04fd641e2a9dd25fbd0c50006210570bccf931d1aea76036d2f517e51afaa869"

    def install
      bin.install "tucp"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Tucp
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/alphauslabs/tucp/releases/download/v0.1.1/tucp_0.1.1_linux_amd64.tar.gz"
      sha256 "ccf26fcbce2a9f5e9b1c85f1f1b33d5e3be28e3d7ab9fb3cd12ac0d616f8e2a0"

      def install
        bin.install "tucp"
      end
    end
  end

  test do
    assert_match /Command line interface for /, shell_output("#{bin}/tucp -h", 0)
  end
end
