# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tucp < Formula
  desc "The official command line interface for Alphaus TrueUnblended Control Plane service."
  homepage "https://github.com/alphauslabs/tucp"
  version "0.4.2"

  on_macos do
    url "https://github.com/alphauslabs/tucp/releases/download/v0.4.2/tucp_0.4.2_darwin_amd64.tar.gz"
    sha256 "fce6b02992800eb52fbc9645b36e994512531fe77653b79f021b649aba7b9d79"

    def install
      bin.install "tucp"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Tucp
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/alphauslabs/tucp/releases/download/v0.4.2/tucp_0.4.2_linux_amd64.tar.gz"
      sha256 "09acb3f8a39b5308c32e0c04c32d7deb0dcc8676f6c185ac9c165d3eff84fad6"

      def install
        bin.install "tucp"
      end
    end
  end

  test do
    assert_match /Command line interface for /, shell_output("#{bin}/tucp -h", 0)
  end
end
